export const ACTION = {
  FETCH_MOVIES_INIT: 'FETCH_MOVIES_INIT',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
  ADD_MOVIE_INIT: 'ADD_MOVIE_INIT',
  ADD_MOVIE_VALIDATION: 'ADD_MOVIE_VALIDATION',
  ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
  ADD_MOVIE_ERROR: 'ADD_MOVIE_ERROR',
  EDIT_MOVIE_FETCH_INIT: 'EDIT_MOVIE_FETCH_INIT',
  EDIT_MOVIE_FETCH_VALIDATION: 'EDIT_MOVIE_FETCH_VALIDATION',
  EDIT_MOVIE_FETCH_SUCCESS: 'EDIT_MOVIE_FETCH_SUCCESS',
  EDIT_MOVIE_FETCH_ERROR: 'EDIT_MOVIE_FETCH_ERROR',
  EDIT_MOVIE_INIT: 'EDIT_MOVIE_INIT',
  EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
  EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR',
  DELETE_MOVIE_INIT: 'DELETE_MOVIE_INIT',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR'
}
