export const ACTION = {
  INIT_APPLICATION: 'INIT_APPLICATION',
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIES_FULFILLED: 'FETCH_MOVIES_FULFILLED',
  FETCH_MOVIES_PENDING: 'FETCH_MOVIES_PENDING',
  FETCH_MOVIES_REJECTED: 'FETCH_MOVIES_REJECTED',
  ADD_MOVIE: 'ADD_MOVIE',
  EDIT_MOVIE: 'EDIT_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE'
}
